# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: Npm@1
  displayName: "Install npm"
  inputs:
    verbose: false

- script: 'npm install -g gatsby-cli'
  displayName: 'Install Gatsby'

- script: 'npm install --save-dev jest babel-jest react-test-renderer babel-preset-gatsby identity-obj-proxy'
  displayName: 'Install test frameworks'

